name: Release (Production)

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up PNPM
        uses: pnpm/action-setup@master
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Bundle
        run: pnpm run build:prod:bundle --all

      - uses: ncipollo/release-action@main
        with:
          artifacts: 'bundle/*'
          makeLatest: true
